wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: CNNClasification
dataset:
  desc: null
  value: SceneImageDataset
epochs:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723000689
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
